application:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key"
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "test_token"
  timeout_milliseconds: 10000
